version: "3.7"

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      # dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./fasteyes_backend:/src/app

  # web:
  #   container_name: "web"
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./fasteyes_frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  # postgres12:
  #   image: postgres:12
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - data:/var/lib/postgresql/data
  #   environment:    
  #     POSTGRES_PASSWORD: 88888888
  #     POSTGRES_USER: postgres

  nginx:
    container_name: "nginx"
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./fasteyes_frontend:/usr/share/nginx/html
    depends_on:
      - api
      # - web
